version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8443:8443"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_USER: cw
      DB_PASSWORD: 1111
      DB_NAME: CourseWork
      DB_PORT: 1433

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "P@ssw0rd!"
      MSSQL_PID: "Express"
      MSSQL_USER: "cw"
      MSSQL_PASSWORD: "1111"
      MSSQL_DATABASE: "CourseWork"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
